site_url: https://dev.blog.remibardon.name
display_url: https://dev.blog.remibardon.name
backend:
  name: git-gateway
  branch: main
media_folder: static/img
public_folder: /img
collections:
  - name: dev_en
    label: Dev post (en)
    folder: content/english/dev
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: Summary
        hint: For list cards
        name: summary
        widget: string
      - label: Description
        hint: For Open Graph
        name: description
        widget: string
        required: false
      - { label: 'Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - label: Publish date
        name: publishDate
        widget: datetime
        required: false
      - label: Last modification date
        name: lastmod
        widget: datetime
        default: '{{now}}'
      - { label: 'Slug', name: 'slug', widget: 'string', required: false }
      - label: Tags
        name: tags
        widget: list
      - label: Draft
        name: draft
        widget: boolean
        required: true
        default: true
      - { label: 'Body', name: 'body', widget: 'markdown' }
